<?php declare(strict_types=1);
namespace App\SiteParserCore\Business\Definition\Database;

interface MigrationDefinitionInterface
{
    public const UP_QUERY_LIST = [
        'CREATE TABLE action (id INT IDENTITY NOT NULL, source_id INT NOT NULL, destination_id INT NOT NULL, creation_date DATETIME2(6) NOT NULL, name NVARCHAR(100) NOT NULL, handler_namespace NVARCHAR(2000) NOT NULL, sort_order INT, is_disable BIT, PRIMARY KEY (id))',
        'CREATE INDEX IDX_47CC8C92953C1C61 ON action (source_id)',
        'CREATE INDEX IDX_47CC8C92816C6140 ON action (destination_id)',
        'CREATE TABLE destination (id INT IDENTITY NOT NULL, output_id INT NOT NULL, creation_date DATETIME2(6) NOT NULL, name NVARCHAR(100) NOT NULL, handler_namespace NVARCHAR(2000) NOT NULL, PRIMARY KEY (id))',
        'CREATE INDEX IDX_3EC63EAADE097880 ON destination (output_id)',
        'CREATE TABLE group_parameters (id INT IDENTITY NOT NULL, group_id INT NOT NULL, parameter_id INT NOT NULL, creation_date DATETIME2(6) NOT NULL, PRIMARY KEY (id))',
        'CREATE INDEX IDX_D15E294CFE54D947 ON group_parameters (group_id)',
        'CREATE INDEX IDX_D15E294C7C56DBD6 ON group_parameters (parameter_id)',
        'CREATE TABLE owner (id INT IDENTITY NOT NULL, parser_id INT, creation_date DATETIME2(6) NOT NULL, name NVARCHAR(100) NOT NULL, url VARCHAR(MAX) NOT NULL, PRIMARY KEY (id))',
        'CREATE INDEX IDX_CF60E67CF54E453B ON owner (parser_id)',
        'CREATE TABLE parameter (id INT IDENTITY NOT NULL, creation_date DATETIME2(6) NOT NULL, name NVARCHAR(100) NOT NULL, PRIMARY KEY (id))',
        'CREATE TABLE parameter_group (id INT IDENTITY NOT NULL, creation_date DATETIME2(6) NOT NULL, name NVARCHAR(100) NOT NULL, PRIMARY KEY (id))',
        'CREATE TABLE parameter_tree (id INT IDENTITY NOT NULL, parent_id INT NOT NULL, child_id INT NOT NULL, creation_date DATETIME2(6) NOT NULL, PRIMARY KEY (id))',
        'CREATE INDEX IDX_18305DD9727ACA70 ON parameter_tree (parent_id)',
        'CREATE INDEX IDX_18305DD9DD62C21B ON parameter_tree (child_id)',
        'CREATE TABLE parser (id INT IDENTITY NOT NULL, creation_date DATETIME2(6) NOT NULL, name NVARCHAR(100) NOT NULL, sort_order INT, is_disable BIT, PRIMARY KEY (id))',
        'CREATE TABLE parser_actions (id INT IDENTITY NOT NULL, parser_id INT NOT NULL, action_id INT NOT NULL, creation_date DATETIME2(6) NOT NULL, PRIMARY KEY (id))',
        'CREATE INDEX IDX_BAB9095CF54E453B ON parser_actions (parser_id)',
        'CREATE INDEX IDX_BAB9095C9D32F035 ON parser_actions (action_id)',
        'CREATE TABLE parser_tree (id INT IDENTITY NOT NULL, parent_id INT NOT NULL, child_id INT NOT NULL, creation_date DATETIME2(6) NOT NULL, PRIMARY KEY (id))',
        'CREATE INDEX IDX_E457E723727ACA70 ON parser_tree (parent_id)',
        'CREATE INDEX IDX_E457E723DD62C21B ON parser_tree (child_id)',
        'CREATE TABLE source (id INT IDENTITY NOT NULL, input_id INT NOT NULL, creation_date DATETIME2(6) NOT NULL, name NVARCHAR(100) NOT NULL, handler_namespace NVARCHAR(2000) NOT NULL, PRIMARY KEY (id))',
        'CREATE INDEX IDX_5F8A7F7336421AD6 ON source (input_id)',
        'CREATE TABLE value (id INT IDENTITY NOT NULL, parameter_id INT NOT NULL, creation_date DATETIME2(6) NOT NULL, value VARCHAR(MAX), PRIMARY KEY (id))',
        'CREATE INDEX IDX_1D7758347C56DBD6 ON value (parameter_id)',
        'ALTER TABLE action ADD CONSTRAINT FK_47CC8C92953C1C61 FOREIGN KEY (source_id) REFERENCES source (id)',
        'ALTER TABLE action ADD CONSTRAINT FK_47CC8C92816C6140 FOREIGN KEY (destination_id) REFERENCES destination (id)',
        'ALTER TABLE destination ADD CONSTRAINT FK_3EC63EAADE097880 FOREIGN KEY (output_id) REFERENCES parameter (id)',
        'ALTER TABLE group_parameters ADD CONSTRAINT FK_D15E294CFE54D947 FOREIGN KEY (group_id) REFERENCES parameter_group (id)',
        'ALTER TABLE group_parameters ADD CONSTRAINT FK_D15E294C7C56DBD6 FOREIGN KEY (parameter_id) REFERENCES parameter (id)',
        'ALTER TABLE owner ADD CONSTRAINT FK_CF60E67CF54E453B FOREIGN KEY (parser_id) REFERENCES parser (id)',
        'ALTER TABLE parameter_tree ADD CONSTRAINT FK_18305DD9727ACA70 FOREIGN KEY (parent_id) REFERENCES parameter (id)',
        'ALTER TABLE parameter_tree ADD CONSTRAINT FK_18305DD9DD62C21B FOREIGN KEY (child_id) REFERENCES parameter (id)',
        'ALTER TABLE parser_actions ADD CONSTRAINT FK_BAB9095CF54E453B FOREIGN KEY (parser_id) REFERENCES parser (id)',
        'ALTER TABLE parser_actions ADD CONSTRAINT FK_BAB9095C9D32F035 FOREIGN KEY (action_id) REFERENCES action (id)',
        'ALTER TABLE parser_tree ADD CONSTRAINT FK_E457E723727ACA70 FOREIGN KEY (parent_id) REFERENCES parser (id)',
        'ALTER TABLE parser_tree ADD CONSTRAINT FK_E457E723DD62C21B FOREIGN KEY (child_id) REFERENCES parser (id)',
        'ALTER TABLE source ADD CONSTRAINT FK_5F8A7F7336421AD6 FOREIGN KEY (input_id) REFERENCES parameter (id)',
        'ALTER TABLE value ADD CONSTRAINT FK_1D7758347C56DBD6 FOREIGN KEY (parameter_id) REFERENCES parameter (id)',
    ];

    public const DOWN_QUERY_LIST = [
        'ALTER TABLE parser_actions DROP CONSTRAINT FK_BAB9095C9D32F035',
        'ALTER TABLE action DROP CONSTRAINT FK_47CC8C92816C6140',
        'ALTER TABLE destination DROP CONSTRAINT FK_3EC63EAADE097880',
        'ALTER TABLE group_parameters DROP CONSTRAINT FK_D15E294C7C56DBD6',
        'ALTER TABLE parameter_tree DROP CONSTRAINT FK_18305DD9727ACA70',
        'ALTER TABLE parameter_tree DROP CONSTRAINT FK_18305DD9DD62C21B',
        'ALTER TABLE source DROP CONSTRAINT FK_5F8A7F7336421AD6',
        'ALTER TABLE value DROP CONSTRAINT FK_1D7758347C56DBD6',
        'ALTER TABLE group_parameters DROP CONSTRAINT FK_D15E294CFE54D947',
        'ALTER TABLE owner DROP CONSTRAINT FK_CF60E67CF54E453B',
        'ALTER TABLE parser_actions DROP CONSTRAINT FK_BAB9095CF54E453B',
        'ALTER TABLE parser_tree DROP CONSTRAINT FK_E457E723727ACA70',
        'ALTER TABLE parser_tree DROP CONSTRAINT FK_E457E723DD62C21B',
        'ALTER TABLE action DROP CONSTRAINT FK_47CC8C92953C1C61',
        'DROP TABLE action',
        'DROP TABLE destination',
        'DROP TABLE group_parameters',
        'DROP TABLE owner',
        'DROP TABLE parameter',
        'DROP TABLE parameter_group',
        'DROP TABLE parameter_tree',
        'DROP TABLE parser',
        'DROP TABLE parser_actions',
        'DROP TABLE parser_tree',
        'DROP TABLE source',
        'DROP TABLE value',
    ];
}